databases:
  - name: crms-db
    plan: free
    databaseName: crms

services:
  # === Django API ===
  - type: web
    name: crms-api
    runtime: python
    rootDir: backend
    buildCommand: ./build.sh
    startCommand: python -m gunicorn backend.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crms-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_ORIGIN
        value: ""  # set mo 'to after live ang frontend

  # === React (Vite) ===
  - type: web
    name: crms-frontend
    runtime: static
    rootDir: frontend
    buildCommand: VITE_API_BASE=https://crms-api.onrender.com npm ci && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
